const Database = require('better-sqlite3');
const db = new Database('data/local.db');
console.log('=== Suppliers Table ===');
console.log(db.prepare('PRAGMA table_info(suppliers)').all());
console.log('\n=== Projects Table ===');
console.log(db.prepare('PRAGMA table_info(projects)').all());
console.log('\n=== Responses Table ===');
console.log(db.prepare('PRAGMA table_info(responses)').all());
console.log('\n=== Supplier Project Links Table ===');
console.log(db.prepare('PRAGMA table_info(supplier_project_links)').all());
db.close();
